export interface PhotoItem {
  src: string;
  tagline: string;
  shortLabel: string;
  caption: string;
  tag: string;
  fit?: 'contain' | 'cover';
  storyTitle?: string;
  storyNarrative?: string;
  accompaniedBy?: string;
  milestoneEra?: string;
}

export const photoDataset: PhotoItem[] = [
  {
    src: "/images/photo_25.jpg",
    tagline: "Royal Grace in Pattu Saree 👑✨",
    shortLabel: "Royal Grace 👑",
    caption: "Timeless royalty in sea-green pattu saree & gold jewelry 👑🪔",
    tag: "divija_solo",
    storyTitle: "Royal Majesty · The Sea-Green Pattu Saree 👑",
    storyNarrative: "Draped in regal sea-green silk with pure woven gold borders, Divija captured an effortless poise that took everyone's breath away. Her warm smile and heirloom temple jewelry radiated timeless royal grace, celebrating the queen she is every single day.",
    accompaniedBy: "Family & Loved Ones",
    milestoneEra: "Royal Gala Milestone",
  },
  {
    src: "/images/photo_12.jpg",
    tagline: "Traditional Day Diva · KMC 🌺💃",
    shortLabel: "Traditional Diva 🌺",
    caption: "‘Day 5 Traditional Day’ — slaying in red & gold half-saree at KMC 🌺💃",
    tag: "divija_solo",
    storyTitle: "Traditional Day Slaying · KMC Aaravya Fest 🌺💃",
    storyNarrative: "The Kakatiya Medical College campus was buzzing with music and colors on Day 5 Traditional Day. Slaying in a vivid crimson and gold half-saree with fresh jasmine, Divija's laughter and celebratory spirit made the entire quad stop and smile.",
    accompaniedBy: "KMC Med School Batchmates",
    milestoneEra: "KMC Warangal Campus",
  },
  {
    src: "/images/photo_18.jpg",
    tagline: "Medico Divija · Pediatric Rounds 🩺👶",
    shortLabel: "Pediatric Rounds 🩺",
    caption: "Divija on pediatric rounds — gentle warmth for the tiniest smiles 🩺👶💕",
    tag: "divija_solo",
    storyTitle: "Medico Divija · Pediatric Wards & Little Hearts 🩺👶",
    storyNarrative: "During her pediatric clinical posting at KMC hospital, Divija's gentle touch and bright dimpled smile melted away the tears of little children. A true healer who proves medicine is an art of genuine kindness and heart.",
    accompaniedBy: "Pediatric Care Team",
    milestoneEra: "MBBS Clinical Rounds",
  },
  {
    src: "/images/photo_19.jpg",
    tagline: "Suspension Bridge Breezes 🌲✨",
    shortLabel: "Nature Trails 🌲",
    caption: "Suspension bridge trail in polka dots — nature breeze & happy vibes 🌲🌿✨",
    tag: "divija_solo",
    storyTitle: "Suspension Bridge Breezes & Nature Trails 🌲🌿",
    storyNarrative: "High above the river canopy in playful polka dots, Divija crossed the suspension bridge with pure carefree joy. Breathing in the fresh mountain air, it was a moment of true peace and spontaneous outdoor adventure.",
    accompaniedBy: "Travel Crew",
    milestoneEra: "College Getaway Trip",
  },
  {
    src: "/images/photo_24.jpg",
    tagline: "Fairy Lights & Dimpled Smiles 💖✨",
    shortLabel: "Fairy Lights 💖",
    caption: "Illuminated sangeet fairy lights & dimpled smiles in hot-pink saree 💖✨🪔",
    tag: "divija_solo",
    storyTitle: "Fairy Lights & Dimpled Sangeet Magic 💖✨",
    storyNarrative: "Under an illuminated canopy of warm fairy lights, Divija dazzled in a hot-pink festive saree. When the music started and she turned with that signature dimple, the whole celebration felt like pure starlight.",
    accompaniedBy: "Sangeet Celebrants",
    milestoneEra: "Festive Family Jubilee",
  },
  {
    src: "/images/photo_29.jpg",
    tagline: "Canteen Laughs & Blessings 🪔✨",
    shortLabel: "Canteen Vibes 🪔",
    caption: "‘Just another Wednesday!’ — canteen laughs & festive Ganesh blessings 🪔🍲✨",
    tag: "divija_solo",
    storyTitle: "Canteen Laughs & Ganesh Blessings 🪔🍲",
    storyNarrative: "‘Just another Wednesday!’ An iconic college afternoon filled with delicious canteen bites, endless inside jokes, and festive blessings that brought the whole squad closer than ever.",
    accompaniedBy: "Canteen Squad",
    milestoneEra: "Hostel & Canteen Days",
  },
  {
    src: "/images/photo_30.jpg",
    tagline: "Squad Mall Mirror Selfie 🛍️👭",
    shortLabel: "Squad Selfie 🛍️",
    caption: "‘The Face of Your Biggest Inspiration’ — mall shopping mirror selfie with the squad 🛍️✨👭",
    tag: "divija_solo",
    storyTitle: "Mall Mirror Selfie with the Squad 🛍️👭",
    storyNarrative: "‘The Face of Your Biggest Inspiration’—a hilarious and chic mirror selfie during an all-out weekend shopping spree. Bagging outfits, coffee cups in hand, and unstoppable giggles.",
    accompaniedBy: "The Girl Gang",
    milestoneEra: "Weekend City Outings",
  },
  {
    src: "/images/photo_37.jpg",
    tagline: "Golden Hour Rooftop Radiance 🌅💛",
    shortLabel: "Golden Hour 🌅",
    caption: "Golden hour rooftop radiance in traditional mustard langa voni 🌅✨💛",
    tag: "divija_solo",
    storyTitle: "Golden Hour Rooftop Radiance 🌅💛",
    storyNarrative: "Bathed in the warm amber glow of the setting sun on the rooftop, dressed in traditional mustard silk. The golden breeze and serene twilight created a photograph that feels like a quiet poem.",
    accompaniedBy: "Sunset Serenity",
    milestoneEra: "Golden Hour Keepsake",
  },
  {
    src: "/images/photo_38.jpg",
    tagline: "Lady Whistledown · Aaravya 🌹💌",
    shortLabel: "Lady Whistledown 🌹",
    caption: "‘Dearest Gentle Reader...’ — Lady Whistledown booth at KMC Aaravya ’25 🌹💌✨",
    tag: "divija_solo",
    storyTitle: "Lady Whistledown's Society Parlor · Aaravya ’25 🌹💌",
    storyNarrative: "‘Dearest Gentle Reader...’ At the college fest Bridgerton photo parlor, Divija posed with quills and vintage floral envelopes, playing the secret society gossip with theatrical elegance and charm.",
    accompaniedBy: "Aaravya Literary Society",
    milestoneEra: "KMC Aaravya ’25",
  },
  {
    src: "/images/photo_40.jpg",
    tagline: "Mint Green Garden Elegance 🌸🤍",
    shortLabel: "Garden Elegance 🌸",
    caption: "Pastel flower arch & sunny garden elegance in mint-green saree 🌸🌿🤍",
    tag: "divija_solo",
    storyTitle: "Sunny Garden Arch & Mint Green Elegance 🌸🤍",
    storyNarrative: "Standing under a pastel floral arch in a pristine mint-green saree, Divija looked fresh as morning dew. The gentle sunlight and garden blooms reflected her pure, generous heart.",
    accompaniedBy: "Garden Gathering",
    milestoneEra: "Springtime Gala",
  },
  {
    src: "/images/photo_27.jpg",
    tagline: "Birthday Sparkler Cake 🎂🎉",
    shortLabel: "Birthday Sparkler 🎂",
    caption: "Birthday girl with fairy-light heart, party hat & sparkler cake! 🎂🎉✨",
    tag: "divija_solo",
    storyTitle: "Midnight Sparkler Cake & Birthday Wishes 🎂🎉",
    storyNarrative: "Surrounded by a glowing fairy-light heart and holding a crackling sparkler candle, Divija made a secret birthday wish. The room erupted in cheers as she cut the cake, celebrating another year of her magic.",
    accompaniedBy: "Midnight Birthday Crew",
    milestoneEra: "Birthday Milestone",
  },
  {
    src: "/images/photo_01.jpg",
    tagline: "Sister Bond with Sreeja 👭💙",
    shortLabel: "Sister Bond 👭",
    caption: "‘Vibing with sisso... 💙’ — rooftop giggles & forever sister bond with Sreeja 👭✨",
    tag: "sister",
    storyTitle: "Sisterhood Forever · Rooftop Secrets with Sreeja 👭💙",
    storyNarrative: "‘Vibing with sisso... 💙’ A candid rooftop sunset filled with sibling banter, shared secrets, and unconditional love. No matter how much life changes, the bond with her sister Sreeja is her forever anchor.",
    accompaniedBy: "Sister Sreeja",
    milestoneEra: "Forever Sister Bond",
  },
  {
    src: "/images/photo_32.jpg",
    tagline: "Campus Reunion with Krushni 💛✨",
    shortLabel: "Bestie Reunion 💛",
    caption: "‘Hey @sunshine... watt ey sudden suprize! 🫶🏼♾️’ — campus reunion with Krushni 💛",
    tag: "bestie",
    storyTitle: "Campus Reunion with Krushni · Sudden Surprises 💛✨",
    storyNarrative: "‘Hey @sunshine... watt ey sudden suprize! 🫶🏼♾️’ When bestie Krushni surprised her on campus, the shrieks of excitement could be heard across the quad. A soulmate friendship that transcends distance.",
    accompaniedBy: "Krushni (Bestie)",
    milestoneEra: "Campus Bestie Reunion",
  },
  {
    src: "/images/photo_33.jpg",
    tagline: "Lawn Laughter & Sunshine 🌸👯‍♀️",
    shortLabel: "Lawn Laughs 🌸",
    caption: "‘aesthetic ❤️ ♾️’ — garden lawn laughter & sweet moments with Krushni 🌸👯‍♀️",
    tag: "bestie",
    storyTitle: "Lawn Laughter & Golden Sunshine with Krushni 🌸👯‍♀️",
    storyNarrative: "‘aesthetic ❤️ ♾️’ Sitting on the green lawns under the afternoon sun, laughing until their stomachs hurt. The kind of effortless bestie warmth that makes the ordinary feel extraordinary.",
    accompaniedBy: "Krushni (Bestie)",
    milestoneEra: "Lawn Chilling Days",
  },
  {
    src: "/images/photo_34.jpg",
    tagline: "Peace Signs & Bestie Hugs ✌️💛",
    shortLabel: "Bestie Hugs ✌️",
    caption: "‘Wednesday 3:43 PM’ — surprise back-hugs & playful peace signs with Krushni ✌️💛🫂",
    tag: "bestie",
    storyTitle: "Peace Signs & Surprise Back-Hugs ✌️💛🫂",
    storyNarrative: "‘Wednesday 3:43 PM’—sneaking up behind with a warm bear hug and flashing peace signs. Unfiltered, candid, and bursting with affection.",
    accompaniedBy: "Krushni (Bestie)",
    milestoneEra: "Midweek Memories",
  },
  {
    src: "/images/photo_35.jpg",
    tagline: "Casual Comfort & Heart Doodles ☕💖",
    shortLabel: "Casual Comfort ☕",
    caption: "Casual days & heart doodles — comfort, peace & true bestie vibes with Krushni 💖☕",
    tag: "bestie",
    storyTitle: "Casual Comfort & Heart Doodles ☕💖",
    storyNarrative: "Comfortable oversized hoodies, hot coffee mugs, and doodling hearts in study notebooks. Pure comfort, quiet peace, and knowing someone has your back through everything.",
    accompaniedBy: "Krushni (Bestie)",
    milestoneEra: "Cozy Study Evenings",
  },
  {
    src: "/images/photo_36.jpg",
    tagline: "La Délicious Cafe Pizza Date 🍕☕",
    shortLabel: "Cafe Date 🍕",
    caption: "‘Monday at La Délicious Cafe’ — pizza dates & heart-to-heart talks with Krushni 🍕☕✨",
    tag: "bestie",
    storyTitle: "La Délicious Cafe Pizza Date 🍕☕✨",
    storyNarrative: "‘Monday at La Délicious Cafe’—steaming slices of pizza, iced coffees, and marathon heart-to-heart conversations dissecting life, medical exams, and dreams for the future.",
    accompaniedBy: "Krushni (Bestie)",
    milestoneEra: "Cafe Dates",
  },
  {
    src: "/images/photo_03.jpg",
    tagline: "Cultural Night with Roomies 💃🔥",
    shortLabel: "Cultural Night 💃",
    caption: "‘Sampradayam tho kudina vinamratha 🙏 Day 7 Culturals’ with Prathima & Bhavana 💃🔥",
    tag: "roommates",
    storyTitle: "Sampradayam Culturals with Roomies Sai Prathima & Bhavana 💃🔥",
    storyNarrative: "‘Sampradayam tho kudina vinamratha 🙏 Day 7 Culturals’. Dressed in coordinated ethnic silks, the hostel room turned into a dance studio before they took over the fest with uncontainable energy.",
    accompaniedBy: "Sai Prathima & Bhavana (Roommates)",
    milestoneEra: "Hostel Roomies Legacy",
  },
  {
    src: "/images/photo_13.jpg",
    tagline: "Carnival Night & Momos Fun 🎪🥟",
    shortLabel: "Carnival Night 🎪",
    caption: "‘Day 4 Carnival Night & Momos Mawa’ — floral maxi dresses & food stall fun 🎪🥟🎈",
    tag: "roommates",
    storyTitle: "Carnival Night & Hot Momos with Roomies 🎪🥟🎈",
    storyNarrative: "‘Day 4 Carnival Night & Momos Mawa!’ Twirling in floral maxi dresses under neon fest banners, hopping from game booths to food stalls, and sharing plates of steaming spicy momos.",
    accompaniedBy: "Sai Prathima & Bhavana (Roommates)",
    milestoneEra: "Carnival Fest Night",
  },
  {
    src: "/images/photo_16.jpg",
    tagline: "Hostel Laughs · Makara Rashi 💅🫣",
    shortLabel: "Hostel Laughs 💅",
    caption: "‘Day 2 With the artists — Team Makara Rashi 🔥’ — nail art & goofy hostel laughter 💅🫣",
    tag: "roommates",
    storyTitle: "Hostel Late-Night Laughs · Team Makara Rashi 💅🫣🔥",
    storyNarrative: "‘Day 2 With the artists — Team Makara Rashi!’ Late-night nail art sessions, goofy gossip, hilarious selfie poses, and laughter echoing down the hostel corridor at 2 AM.",
    accompaniedBy: "Hostel Gang & Roomies",
    milestoneEra: "Hostel Midnight Chaos",
  },
  {
    src: "/images/photo_23.jpg",
    tagline: "Festive Silk with Roommates 🪔✨",
    shortLabel: "Festive Silk 🪔",
    caption: "Festive pattu sarees with roomies Sai Prathima & Bhavana — our second family 🪔✨🏠",
    tag: "roommates",
    storyTitle: "Festive Pattu Silk Celebrations at the Room 🪔✨🏠",
    storyNarrative: "Celebrating festivals away from home made special by roommates who became family. Draped in shimmering silk sarees with flower garlands, creating lifelong festive traditions.",
    accompaniedBy: "Sai Prathima & Bhavana (Roommates)",
    milestoneEra: "Festive Room Family",
  },
  {
    src: "/images/photo_20.jpg",
    tagline: "Waterfall & Beach Adventures 🌊🏖️",
    shortLabel: "Beach Adventures 🌊",
    caption: "College trip adventures — mountain waterfalls & ocean beach waves with the gang 🌊🏖️💦",
    tag: "college",
    storyTitle: "Beach Waves & Mountain Waterfall Adventures 🌊🏖️",
    storyNarrative: "Escaping the hospital wards for a weekend of crashing ocean waves and cool mountain waterfalls. Soaked in sunshine, salty air, and freedom with the med school crew.",
    accompaniedBy: "College Travel Gang",
    milestoneEra: "Med School Trips",
  },
  {
    src: "/images/photo_02.jpg",
    tagline: "Gala Night Celebrations · KMC 🌟🥂",
    shortLabel: "Gala Night 🌟",
    caption: "Culturals lawn night & chandelier gala celebrations with KMC friends 🌟🥂✨",
    tag: "college",
    storyTitle: "Gala Lawn Celebrations & Chandelier Nights 🌟🥂",
    storyNarrative: "Dressed to the nines under the evening chandeliers at the annual KMC Gala. Dancing on the lawns with sparklers, celebrating the journey with the dearest friends.",
    accompaniedBy: "KMC Batchmates",
    milestoneEra: "Annual Gala Premiere",
  },
  {
    src: "/images/photo_39.jpg",
    tagline: "Aarunya ’24 Batch Portrait 🎓🎉",
    shortLabel: "Batch Portrait 🎓",
    caption: "‘Aarunya ’24 Fest’ — stage dance performance & grand KMC auditorium batch portrait 💃🎉🎓",
    tag: "college",
    storyTitle: "Aarunya ’24 Batch Portrait & Stage Finale 🎓🎉💃",
    storyNarrative: "‘Aarunya ’24 Fest’—after an electric stage dance performance, the entire batch gathered in the grand KMC auditorium for a proud, beaming portrait commemorating their journey.",
    accompaniedBy: "KMC Med School Batch of 2024",
    milestoneEra: "Aarunya Fest Finale",
  },
];

export default photoDataset;
